<?php

namespace Mv\BlogBundle\Entity\AdminBlog;

use Doctrine\ORM\EntityRepository;
use Doctrine\Common\Collections\Criteria;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    /**
     * 
     * @return Criteria
     */
    static function getPubliedOrderedCriteria(){
        return  $criteria = Criteria::create()->andWhere(Criteria::expr()->gte('publied', date('Y-m-d H:i:s')))
                                              ->orderBy(array('created' => Criteria::ASC));
    }
}
