<?php

namespace Mv\BlogBundle\Entity\AdminBlog;

use Doctrine\ORM\EntityRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Criteria;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    /**
     * 
     * @return Criteria
     */
    static function getOrderedCriteria($limit = null){
        return  $criteria = Criteria::create()->orderBy(array('publied' => Criteria::DESC))
                                                ->setMaxResults($limit);
    }

    /**
     * 
     * @return Criteria
     */
    static function getPubliedOrderedCriteria($limit = null){
        return self::getOrderedCriteria($limit)->andWhere(Criteria::expr()->lte('publied', new \DateTime('now')));
    }
    
    /**
     * 
     * @return array
     */
    public function findAllOrdered($limit = null){
        $entities = new ArrayCollection($this->findAll());
        
        return $entities->matching(self::getOrderedCriteria($limit))->toArray();
    }

    /**
     * 
     * @return array
     */
    public function findAllPubliedOrdered($limit = null){
        $entities = new ArrayCollection($this->findAll());
        
        return $entities->matching(self::getPubliedOrderedCriteria($limit))->toArray();
    }
    
    public function findByCategoryPubliedOrdered($id){
        $entities = $this->createQueryBuilder('p')
                        ->addSelect('c')
                        ->innerJoin('p.categories', 'c')
                        ->having('c.id = :id')
                        ->setParameter('id', $id)
                        ->getQuery()
                        ->getResult();
        $entities = new ArrayCollection($entities);
        
        return $entities->matching(self::getPubliedOrderedCriteria())->toArray();
    }
}
