<?php

namespace Mv\BlogBundle\Entity\AdminBlog;

use Doctrine\ORM\EntityRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Criteria;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    /**
     * 
     * @return Criteria
     */
    protected function _getPubliedOrderedCriteria(){
        return  $criteria = Criteria::create()->andWhere(Criteria::expr()->gte('publied', date('Y-m-d H:i:s')))
                                              ->orderBy(array('publied' => Criteria::DESC));
    }

    /**
     * 
     * @return array
     */
    public function findAllPubliedOrdered(){        
        $entities = new ArrayCollection($this->findAll());
        
        return $entities->matching($this->_getPubliedOrderedCriteria())->toArray();
    }
    
    public function findByCategoryPubliedOrdered($id){
        $entities = $this->createQueryBuilder('p')
                        ->addSelect('c')
                        ->innerJoin('p.categories', 'c')
                        ->having('c.id = :id')
                        ->setParameter('id', $id)
                        ->getQuery()
                        ->getResult();
        $entities = new ArrayCollection($entities);
        
        return $entities->matching($this->_getPubliedOrderedCriteria())->toArray();
    }
}
